const dataPlayers=[
    {
        "player_id": 10440,
        "fname": "Derrick",
        "lname": "Henry",
        "team": "TEN",
        "team_id": 30,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 10,
            "REC": 9,
            "RCLNG": 23,
            "RCYDS": 74,
            "RUYDS": 240,
            "RUTDS": 3,
            "RUATT": 52,
            "RULNG": 79,
            "DEFTD": 3,
            "FFPTS": 49.4,
            "FFPTS/G": 24.7,
            "TYDS": 314,
            "TTDS": 3,
            "RUYPA": 4.615384615384615,
            "PLAYS": 62,
            "Plays": 62,
            "PAATT\nTRGT": 10,
            "PACMP\nREC": 9,
            "PAYDS\nRCYDS": 74
        },
        "fpts": 49.4,
        "player": "Derrick Henry"
    },
    {
        "player_id": 11202,
        "fname": "Christian",
        "lname": "McCaffrey",
        "team": "CAR",
        "team_id": 15,
        "position": "RB",
        "injured": 1,
        "injury_type": "McCaffrey was forced from Thursday's game with a hamstring injury, and it is unclear if he will play against the Cowboys on October 3.",
        "stats": {
            "GMS": 3,
            "GMST": 3,
            "RCTG": 17,
            "REC": 16,
            "RCLNG": 62,
            "RCYDS": 163,
            "RUYDS": 201,
            "RUTDS": 1,
            "RUATT": 52,
            "RULNG": 44,
            "DEFTD": 1,
            "FFPTS": 42.4,
            "FFPTS/G": 14.1,
            "TYDS": 364,
            "TTDS": 1,
            "RUYPA": 3.8653846153846154,
            "PLAYS": 69,
            "Plays": 69,
            "PAATT\nTRGT": 17,
            "PACMP\nREC": 16,
            "PAYDS\nRCYDS": 163
        },
        "fpts": 42.4,
        "player": "Christian McCaffrey"
    },
    {
        "player_id": 12247,
        "fname": "Nick",
        "lname": "Chubb",
        "team": "CLE",
        "team_id": 29,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 3,
            "REC": 3,
            "RCLNG": 13,
            "RCYDS": 21,
            "RUYDS": 178,
            "RUTDS": 3,
            "RUATT": 26,
            "RULNG": 44,
            "DEFTD": 3,
            "PAFUM": 1,
            "PAFUML": 1,
            "FUML": 1,
            "FUM": 1,
            "FFPTS": 37.9,
            "FFPTS/G": 18.9,
            "TYDS": 199,
            "TTDS": 3,
            "RUYPA": 6.846153846153846,
            "PLAYS": 29,
            "Plays": 29,
            "PAATT\nTRGT": 3,
            "PACMP\nREC": 3,
            "PAYDS\nRCYDS": 21
        },
        "fpts": 37.9,
        "player": "Nick Chubb"
    },
    {
        "player_id": 11445,
        "fname": "Aaron",
        "lname": "Jones",
        "team": "GB",
        "team_id": 14,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 8,
            "REC": 8,
            "RCLNG": 20,
            "RCYDS": 61,
            "RCTDS": 3,
            "RUYDS": 76,
            "RULNGTD": 3,
            "RUTDS": 1,
            "RUATT": 22,
            "RULNG": 12,
            "DEFTD": 4,
            "FFPTS": 37.7,
            "FFPTS/G": 18.9,
            "TYDS": 137,
            "TTDS": 4,
            "RUYPA": 3.4545454545454546,
            "PLAYS": 30,
            "Plays": 30,
            "PAATT\nTRGT": 8,
            "PACMP\nREC": 8,
            "PAYDS\nRCYDS": 61,
            "PATDS\nRCTDS": 3
        },
        "fpts": 37.7,
        "player": "Aaron Jones"
    },
    {
        "player_id": 11296,
        "fname": "Dalvin",
        "lname": "Cook",
        "team": "MIN",
        "team_id": 16,
        "position": "RB",
        "injured": 1,
        "injury_type": "Cook is nursing an ankle sprain, but he is likely to partake in Sunday's showdown with the Seahawks.",
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 10,
            "REC": 8,
            "RCLNG": 23,
            "RCYDS": 60,
            "RUYDS": 192,
            "RUTDS": 1,
            "RUATT": 42,
            "RULNG": 33,
            "DEFTD": 1,
            "PAFUM": 1,
            "PAFUML": 1,
            "FUML": 1,
            "FUM": 1,
            "FFPTS": 31.2,
            "FFPTS/G": 15.6,
            "TYDS": 252,
            "TTDS": 1,
            "RUYPA": 4.571428571428571,
            "PLAYS": 52,
            "Plays": 52,
            "PAATT\nTRGT": 10,
            "PACMP\nREC": 8,
            "PAYDS\nRCYDS": 60
        },
        "fpts": 31.2,
        "player": "Dalvin Cook"
    },
    {
        "player_id": 57023,
        "fname": "Darrell",
        "lname": "Henderson",
        "team": "LAR",
        "team_id": 9,
        "position": "RB",
        "injured": 1,
        "injury_type": "Henderson Jr. exited the previous game due to a rib injury, and it has yet to be established if he will face the Buccaneers on Sunday.",
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 6,
            "REC": 4,
            "RCLNG": 40,
            "RCYDS": 46,
            "RUYDS": 123,
            "RUTDS": 2,
            "RUATT": 29,
            "RULNG": 28,
            "DEFTD": 2,
            "FFPTS": 28.9,
            "FFPTS/G": 14.4,
            "TYDS": 169,
            "TTDS": 2,
            "RUYPA": 4.241379310344827,
            "PLAYS": 35,
            "Plays": 35,
            "PAATT\nTRGT": 6,
            "PACMP\nREC": 4,
            "PAYDS\nRCYDS": 46
        },
        "fpts": 28.9,
        "player": "Darrell Henderson"
    },
    {
        "player_id": 11251,
        "fname": "Joe",
        "lname": "Mixon",
        "team": "CIN",
        "team_id": 23,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 6,
            "REC": 5,
            "RCLNG": 14,
            "RCYDS": 25,
            "RUYDS": 196,
            "RUTDS": 1,
            "RUATT": 49,
            "RULNG": 29,
            "DEFTD": 1,
            "FFPTS": 28.1,
            "FFPTS/G": 14.1,
            "TYDS": 221,
            "TTDS": 1,
            "RUYPA": 4,
            "PLAYS": 55,
            "Plays": 55,
            "PAATT\nTRGT": 6,
            "PACMP\nREC": 5,
            "PAYDS\nRCYDS": 25
        },
        "fpts": 28.1,
        "player": "Joe Mixon"
    },
    {
        "player_id": 11361,
        "fname": "Chris",
        "lname": "Carson",
        "team": "SEA",
        "team_id": 21,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 3,
            "REC": 3,
            "RCLNG": 16,
            "RCYDS": 26,
            "RUYDS": 122,
            "RUTDS": 2,
            "RUATT": 29,
            "RULNG": 41,
            "DEFTD": 2,
            "PAFUM": 1,
            "PAFUML": 1,
            "FUML": 1,
            "FUM": 1,
            "FFPTS": 26.8,
            "FFPTS/G": 13.4,
            "TYDS": 148,
            "TTDS": 2,
            "RUYPA": 4.206896551724138,
            "PLAYS": 32,
            "Plays": 32,
            "PAATT\nTRGT": 3,
            "PACMP\nREC": 3,
            "PAYDS\nRCYDS": 26
        },
        "fpts": 26.8,
        "player": "Chris Carson"
    },
    {
        "player_id": 58149,
        "fname": "David",
        "lname": "Montgomery",
        "team": "CHI",
        "team_id": 27,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 5,
            "REC": 4,
            "RCLNG": 20,
            "RCYDS": 28,
            "RUYDS": 169,
            "RUTDS": 1,
            "RUATT": 36,
            "RULNG": 52,
            "DEFTD": 1,
            "FFPTS": 25.7,
            "FFPTS/G": 12.8,
            "TYDS": 197,
            "TTDS": 1,
            "RUYPA": 4.694444444444445,
            "PLAYS": 41,
            "Plays": 41,
            "PAATT\nTRGT": 5,
            "PACMP\nREC": 4,
            "PAYDS\nRCYDS": 28
        },
        "fpts": 25.7,
        "player": "David Montgomery"
    },
    {
        "player_id": 8302,
        "fname": "Cordarrelle",
        "lname": "Patterson",
        "team": "ATL",
        "team_id": 12,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 1,
            "KRYDS": 52,
            "KRS": 2,
            "KRLNG": 52,
            "KRAVG": 52,
            "RCTG": 9,
            "REC": 7,
            "RCLNG": 35,
            "RCYDS": 71,
            "RCTDS": 1,
            "RUYDS": 65,
            "RULNGTD": 1,
            "RUTDS": 1,
            "RUATT": 14,
            "RULNG": 24,
            "DEFTD": 2,
            "PAFUM": 1,
            "FUM": 1,
            "AST": 1,
            "FFPTS": 25.6,
            "FFPTS/G": 12.8,
            "TYDS": 136,
            "TTDS": 2,
            "RUYPA": 4.642857142857143,
            "PLAYS": 23,
            "Plays": 23,
            "PAATT\nTRGT": 9,
            "PACMP\nREC": 7,
            "PAYDS\nRCYDS": 71,
            "PATDS\nRCTDS": 1
        },
        "fpts": 25.6,
        "player": "Cordarrelle Patterson"
    },
    {
        "player_id": 9838,
        "fname": "Melvin",
        "lname": "Gordon III",
        "team": "DEN",
        "team_id": 8,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 5,
            "REC": 5,
            "RCLNG": 43,
            "RCYDS": 55,
            "RUYDS": 132,
            "RUTDS": 1,
            "RUATT": 24,
            "RULNG": 78,
            "DEFTD": 1,
            "FFPTS": 24.7,
            "FFPTS/G": 12.3,
            "TYDS": 187,
            "TTDS": 1,
            "RUYPA": 5.5,
            "PLAYS": 29,
            "Plays": 29,
            "PAATT\nTRGT": 5,
            "PACMP\nREC": 5,
            "PAYDS\nRCYDS": 55
        },
        "fpts": 24.7,
        "player": "Melvin Gordon III"
    },
    {
        "player_id": 36011806,
        "fname": "Ty'Son",
        "lname": "Williams",
        "team": "BAL",
        "team_id": 24,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 6,
            "REC": 5,
            "RCLNG": 30,
            "RCYDS": 45,
            "RUYDS": 142,
            "RUTDS": 1,
            "RUATT": 22,
            "RULNG": 55,
            "DEFTD": 1,
            "PAFUM": 1,
            "FUM": 1,
            "FFPTS": 24.7,
            "FFPTS/G": 12.3,
            "TYDS": 187,
            "TTDS": 1,
            "RUYPA": 6.454545454545454,
            "PLAYS": 28,
            "Plays": 28,
            "PAATT\nTRGT": 6,
            "PACMP\nREC": 5,
            "PAYDS\nRCYDS": 45
        },
        "fpts": 24.7,
        "player": "Ty'Son Williams"
    },
    {
        "player_id": 56241,
        "fname": "Tony",
        "lname": "Pollard",
        "team": "DAL",
        "team_id": 6,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "KRYDS": 71,
            "KRS": 3,
            "KRLNG": 24,
            "KRAVG": 23.670000076293945,
            "RCTG": 7,
            "REC": 7,
            "RCLNG": 24,
            "RCYDS": 60,
            "RUYDS": 123,
            "RUTDS": 1,
            "RUATT": 16,
            "RULNG": 39,
            "DEFTD": 1,
            "FFPTS": 24.3,
            "FFPTS/G": 12.2,
            "TYDS": 183,
            "TTDS": 1,
            "RUYPA": 7.6875,
            "PLAYS": 23,
            "Plays": 23,
            "PAATT\nTRGT": 7,
            "PACMP\nREC": 7,
            "PAYDS\nRCYDS": 60
        },
        "fpts": 24.3,
        "player": "Tony Pollard"
    },
    {
        "player_id": 26054266,
        "fname": "D'Andre",
        "lname": "Swift",
        "team": "DET",
        "team_id": 2,
        "position": "RB",
        "injured": 1,
        "injury_type": "Swift is bothered by a groin injury, and it has yet to be determined if he will lace up against the Ravens on Sunday.",
        "stats": {
            "GMS": 2,
            "RCTG": 16,
            "REC": 12,
            "RCLNG": 59,
            "RCYDS": 106,
            "RCTDS": 1,
            "RUYDS": 76,
            "RULNGTD": 1,
            "RUATT": 19,
            "RULNG": 28,
            "DEFTD": 1,
            "FFPTS": 24.2,
            "FFPTS/G": 12.1,
            "TYDS": 182,
            "TTDS": 1,
            "RUYPA": 4,
            "PLAYS": 35,
            "Plays": 35,
            "PAATT\nTRGT": 16,
            "PACMP\nREC": 12,
            "PAYDS\nRCYDS": 106,
            "PATDS\nRCTDS": 1
        },
        "fpts": 24.2,
        "player": "D'Andre Swift"
    },
    {
        "player_id": 58122,
        "fname": "Damien",
        "lname": "Harris",
        "team": "NE",
        "team_id": 1,
        "position": "RB",
        "injured": 1,
        "injury_type": "Harris is bothered by a finger injury, and it has yet to be announced if he will lace up against the Saints on Sunday.",
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 4,
            "REC": 3,
            "RCLNG": 11,
            "RCYDS": 19,
            "RUYDS": 162,
            "RUTDS": 1,
            "RUATT": 39,
            "RULNG": 61,
            "DEFTD": 1,
            "PAFUM": 1,
            "PAFUML": 1,
            "FUML": 1,
            "FUM": 1,
            "FFPTS": 24.1,
            "FFPTS/G": 12.1,
            "TYDS": 181,
            "TTDS": 1,
            "RUYPA": 4.153846153846154,
            "PLAYS": 43,
            "Plays": 43,
            "PAATT\nTRGT": 4,
            "PACMP\nREC": 3,
            "PAYDS\nRCYDS": 19
        },
        "fpts": 24.1,
        "player": "Damien Harris"
    },
    {
        "player_id": 11578,
        "fname": "Austin",
        "lname": "Ekeler",
        "team": "LAC",
        "team_id": 3,
        "position": "RB",
        "injured": 1,
        "injury_type": "Ekeler is expected to take the field against the Chiefs on Sunday despite an ankle injury.",
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 9,
            "REC": 9,
            "RCLNG": 20,
            "RCYDS": 61,
            "RUYDS": 111,
            "RUTDS": 1,
            "RUATT": 24,
            "RULNG": 34,
            "DEFTD": 1,
            "FFPTS": 23.2,
            "FFPTS/G": 11.6,
            "TYDS": 172,
            "TTDS": 1,
            "RUYPA": 4.625,
            "PLAYS": 33,
            "Plays": 33,
            "PAATT\nTRGT": 9,
            "PACMP\nREC": 9,
            "PAYDS\nRCYDS": 61
        },
        "fpts": 23.2,
        "player": "Austin Ekeler"
    },
    {
        "player_id": 58023,
        "fname": "Devin",
        "lname": "Singletary",
        "team": "BUF",
        "team_id": 25,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 1,
            "RCTG": 8,
            "REC": 5,
            "RCLNG": 11,
            "RCYDS": 17,
            "RUYDS": 154,
            "RUTDS": 1,
            "RUATT": 24,
            "RULNG": 71,
            "DEFTD": 1,
            "PAFUM": 3,
            "FUM": 3,
            "FFPTS": 23.1,
            "FFPTS/G": 11.6,
            "TYDS": 171,
            "TTDS": 1,
            "RUYPA": 6.416666666666667,
            "PLAYS": 32,
            "Plays": 32,
            "PAATT\nTRGT": 8,
            "PACMP\nREC": 5,
            "PAYDS\nRCYDS": 17
        },
        "fpts": 23.1,
        "player": "Devin Singletary"
    },
    {
        "player_id": 39629407,
        "fname": "Elijah",
        "lname": "Mitchell",
        "team": "SF",
        "team_id": 32,
        "position": "RB",
        "injured": 1,
        "injury_type": "Mitchell was removed from the last contest with a right shoulder injury, and it has yet to be established if he will suit up in Sunday's matchup versus the Packers.",
        "stats": {
            "GMS": 2,
            "GMST": 1,
            "RCTG": 2,
            "REC": 2,
            "RCLNG": 11,
            "RCYDS": 11,
            "RUYDS": 146,
            "RUTDS": 1,
            "RUATT": 36,
            "RULNG": 48,
            "DEFTD": 1,
            "FFPTS": 21.7,
            "FFPTS/G": 10.8,
            "TYDS": 157,
            "TTDS": 1,
            "RUYPA": 4.055555555555555,
            "PLAYS": 38,
            "Plays": 38,
            "PAATT\nTRGT": 2,
            "PACMP\nREC": 2,
            "PAYDS\nRCYDS": 11
        },
        "fpts": 21.7,
        "player": "Elijah Mitchell"
    },
    {
        "player_id": 11447,
        "fname": "Jamaal",
        "lname": "Williams",
        "team": "DET",
        "team_id": 2,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 12,
            "REC": 11,
            "RCLNG": 17,
            "RCYDS": 68,
            "RUYDS": 79,
            "RUTDS": 1,
            "RUATT": 16,
            "RULNG": 28,
            "DEFTD": 1,
            "FFPTS": 20.7,
            "FFPTS/G": 10.3,
            "TYDS": 147,
            "TTDS": 1,
            "RUYPA": 4.9375,
            "PLAYS": 28,
            "Plays": 28,
            "PAATT\nTRGT": 12,
            "PACMP\nREC": 11,
            "PAYDS\nRCYDS": 68
        },
        "fpts": 20.7,
        "player": "Jamaal Williams"
    },
    {
        "player_id": 4824,
        "fname": "Mark",
        "lname": "Ingram",
        "team": "HOU",
        "team_id": 11,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 3,
            "GMST": 3,
            "RCTG": 4,
            "REC": 2,
            "RCLNG": -2,
            "RCYDS": -2,
            "RUYDS": 147,
            "RUTDS": 1,
            "RUATT": 46,
            "RULNG": 25,
            "DEFTD": 1,
            "FFPTS": 20.5,
            "FFPTS/G": 6.8,
            "TYDS": 145,
            "TTDS": 1,
            "RUYPA": 3.1956521739130435,
            "PLAYS": 50,
            "Plays": 50,
            "PAATT\nTRGT": 4,
            "PACMP\nREC": 2,
            "PAYDS\nRCYDS": -2
        },
        "fpts": 20.5,
        "player": "Mark Ingram"
    },
    {
        "player_id": 10367,
        "fname": "Ezekiel",
        "lname": "Elliott",
        "team": "DAL",
        "team_id": 6,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 4,
            "REC": 4,
            "RCLNG": 17,
            "RCYDS": 32,
            "RUYDS": 104,
            "RUTDS": 1,
            "RUATT": 27,
            "RULNG": 32,
            "DEFTD": 1,
            "FFPTS": 19.6,
            "FFPTS/G": 9.8,
            "TYDS": 136,
            "TTDS": 1,
            "RUYPA": 3.8518518518518516,
            "PLAYS": 31,
            "Plays": 31,
            "PAATT\nTRGT": 4,
            "PACMP\nREC": 4,
            "PAYDS\nRCYDS": 32
        },
        "fpts": 19.6,
        "player": "Ezekiel Elliott"
    },
    {
        "player_id": 40366548,
        "fname": "Najee",
        "lname": "Harris",
        "team": "PIT",
        "team_id": 18,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 8,
            "REC": 6,
            "RCLNG": 29,
            "RCYDS": 47,
            "RCTDS": 1,
            "RUYDS": 83,
            "RULNGTD": 1,
            "RUATT": 26,
            "RULNG": 32,
            "DEFTD": 1,
            "FFPTS": 19,
            "FFPTS/G": 9.5,
            "TYDS": 130,
            "TTDS": 1,
            "RUYPA": 3.1923076923076925,
            "PLAYS": 34,
            "Plays": 34,
            "PAATT\nTRGT": 8,
            "PACMP\nREC": 6,
            "PAYDS\nRCYDS": 47,
            "PATDS\nRCTDS": 1
        },
        "fpts": 19,
        "player": "Najee Harris"
    },
    {
        "player_id": 8711,
        "fname": "James",
        "lname": "White",
        "team": "NE",
        "team_id": 1,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RCTG": 13,
            "REC": 12,
            "RCLNG": 54,
            "RCYDS": 94,
            "RUYDS": 32,
            "RUTDS": 1,
            "RUATT": 9,
            "RULNG": 17,
            "DEFTD": 1,
            "FFPTS": 18.6,
            "FFPTS/G": 9.3,
            "TYDS": 126,
            "TTDS": 1,
            "RUYPA": 3.5555555555555554,
            "PLAYS": 22,
            "Plays": 22,
            "PAATT\nTRGT": 13,
            "PACMP\nREC": 12,
            "PAYDS\nRCYDS": 94
        },
        "fpts": 18.6,
        "player": "James White"
    },
    {
        "player_id": 8349,
        "fname": "Latavius",
        "lname": "Murray",
        "team": "BAL",
        "team_id": 24,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RUYDS": 64,
            "RUTDS": 2,
            "RUATT": 19,
            "RULNG": 16,
            "DEFTD": 2,
            "FFPTS": 18.4,
            "FFPTS/G": 9.2,
            "TYDS": 64,
            "TTDS": 2,
            "RUYPA": 3.3684210526315788,
            "PLAYS": 19,
            "Plays": 19
        },
        "fpts": 18.4,
        "player": "Latavius Murray"
    },
    {
        "player_id": 11249,
        "fname": "Alvin",
        "lname": "Kamara",
        "team": "NO",
        "team_id": 5,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 10,
            "REC": 7,
            "RCLNG": 11,
            "RCYDS": 33,
            "RCTDS": 1,
            "RUYDS": 88,
            "RULNGTD": 1,
            "RUATT": 28,
            "RULNG": 19,
            "DEFTD": 1,
            "FFPTS": 18.1,
            "FFPTS/G": 9.1,
            "TYDS": 121,
            "TTDS": 1,
            "RUYPA": 3.142857142857143,
            "PLAYS": 38,
            "Plays": 38,
            "PAATT\nTRGT": 10,
            "PACMP\nREC": 7,
            "PAYDS\nRCYDS": 33,
            "PATDS\nRCTDS": 1
        },
        "fpts": 18.1,
        "player": "Alvin Kamara"
    },
    {
        "player_id": 12150,
        "fname": "Chase",
        "lname": "Edmonds",
        "team": "ARI",
        "team_id": 26,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 9,
            "REC": 9,
            "RCLNG": 49,
            "RCYDS": 72,
            "RUYDS": 109,
            "RUATT": 20,
            "RULNG": 30,
            "FFPTS": 18.1,
            "FFPTS/G": 9.1,
            "TYDS": 181,
            "RUYPA": 5.45,
            "PLAYS": 29,
            "Plays": 29,
            "PAATT\nTRGT": 9,
            "PACMP\nREC": 9,
            "PAYDS\nRCYDS": 72
        },
        "fpts": 18.1,
        "player": "Chase Edmonds"
    },
    {
        "player_id": 26054213,
        "fname": "Antonio",
        "lname": "Gibson",
        "team": "WAS",
        "team_id": 4,
        "position": "RB",
        "injured": 1,
        "injury_type": "Gibson is bothered by a shoulder injury, but it is projected that he will face the Bills on Sunday.",
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 7,
            "REC": 5,
            "RCLNG": 15,
            "RCYDS": 22,
            "RUYDS": 159,
            "RUATT": 33,
            "RULNG": 41,
            "PAFUM": 2,
            "PAFUML": 1,
            "FUML": 1,
            "FUM": 2,
            "FFPTS": 18.1,
            "FFPTS/G": 9.1,
            "TYDS": 181,
            "RUYPA": 4.818181818181818,
            "PLAYS": 40,
            "Plays": 40,
            "PAATT\nTRGT": 7,
            "PACMP\nREC": 5,
            "PAYDS\nRCYDS": 22
        },
        "fpts": 18.1,
        "player": "Antonio Gibson"
    },
    {
        "player_id": 11279,
        "fname": "Kareem",
        "lname": "Hunt",
        "team": "CLE",
        "team_id": 29,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RCTG": 4,
            "REC": 4,
            "RCLNG": 21,
            "RCYDS": 30,
            "RUYDS": 84,
            "RUTDS": 1,
            "RUATT": 19,
            "RULNG": 28,
            "DEFTD": 1,
            "FFPTS": 17.4,
            "FFPTS/G": 8.7,
            "TYDS": 114,
            "TTDS": 1,
            "RUYPA": 4.421052631578948,
            "PLAYS": 23,
            "Plays": 23,
            "PAATT\nTRGT": 4,
            "PACMP\nREC": 4,
            "PAYDS\nRCYDS": 30
        },
        "fpts": 17.4,
        "player": "Kareem Hunt"
    },
    {
        "player_id": 12356,
        "fname": "Phillip",
        "lname": "Lindsay",
        "team": "HOU",
        "team_id": 11,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 3,
            "RCTG": 2,
            "REC": 1,
            "RCLNG": 22,
            "RCYDS": 22,
            "RCTDS": 1,
            "RUYDS": 32,
            "RULNGTD": 1,
            "RUTDS": 1,
            "RUATT": 20,
            "RULNG": 16,
            "DEFTD": 2,
            "FFPTS": 17.4,
            "FFPTS/G": 5.8,
            "TYDS": 54,
            "TTDS": 2,
            "RUYPA": 1.6,
            "PLAYS": 22,
            "Plays": 22,
            "PAATT\nTRGT": 2,
            "PACMP\nREC": 1,
            "PAYDS\nRCYDS": 22,
            "PATDS\nRCTDS": 1
        },
        "fpts": 17.4,
        "player": "Phillip Lindsay"
    },
    {
        "player_id": 57049,
        "fname": "Miles",
        "lname": "Sanders",
        "team": "PHI",
        "team_id": 28,
        "position": "RB",
        "injured": 1,
        "injury_type": "Sanders is bothered by a chest injury, and it is up in the air if he will be available for Monday's battle with the Cowboys.",
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 7,
            "REC": 5,
            "RCLNG": 29,
            "RCYDS": 43,
            "RUYDS": 129,
            "RUATT": 28,
            "RULNG": 33,
            "FFPTS": 17.2,
            "FFPTS/G": 8.6,
            "TYDS": 172,
            "RUYPA": 4.607142857142857,
            "PLAYS": 35,
            "Plays": 35,
            "PAATT\nTRGT": 7,
            "PACMP\nREC": 5,
            "PAYDS\nRCYDS": 43
        },
        "fpts": 17.2,
        "player": "Miles Sanders"
    },
    {
        "player_id": 26055201,
        "fname": "Jonathan",
        "lname": "Taylor",
        "team": "IND",
        "team_id": 19,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 8,
            "REC": 7,
            "RCLNG": 17,
            "RCYDS": 62,
            "RUYDS": 107,
            "RUATT": 32,
            "RULNG": 25,
            "FFPTS": 16.9,
            "FFPTS/G": 8.4,
            "TYDS": 169,
            "RUYPA": 3.34375,
            "PLAYS": 40,
            "Plays": 40,
            "PAATT\nTRGT": 8,
            "PACMP\nREC": 7,
            "PAYDS\nRCYDS": 62
        },
        "fpts": 16.9,
        "player": "Jonathan Taylor"
    },
    {
        "player_id": 10787,
        "fname": "J.D.",
        "lname": "McKissic",
        "team": "WAS",
        "team_id": 4,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RCTG": 7,
            "REC": 5,
            "RCLNG": 56,
            "RCYDS": 83,
            "RUYDS": 18,
            "RUTDS": 1,
            "RUATT": 5,
            "RULNG": 12,
            "DEFTD": 1,
            "FFPTS": 16.1,
            "FFPTS/G": 8.1,
            "TYDS": 101,
            "TTDS": 1,
            "RUYPA": 3.6,
            "PLAYS": 12,
            "Plays": 12,
            "PAATT\nTRGT": 7,
            "PACMP\nREC": 5,
            "PAYDS\nRCYDS": 83
        },
        "fpts": 16.1,
        "player": "J.D. McKissic"
    },
    {
        "player_id": 56036,
        "fname": "Josh",
        "lname": "Jacobs",
        "team": "LVR",
        "team_id": 10,
        "position": "RB",
        "injured": 1,
        "injury_type": "Jacobs sat out the last game managing injuries to his ankle and toe, and it is unknown if he will dress for Sunday's clash with the Dolphins.",
        "stats": {
            "GMS": 1,
            "GMST": 1,
            "RCTG": 2,
            "REC": 1,
            "RCLNG": 6,
            "RCYDS": 6,
            "RUYDS": 34,
            "RUTDS": 2,
            "RUATT": 10,
            "RULNG": 15,
            "DEFTD": 2,
            "FFPTS": 16,
            "FFPTS/G": 16,
            "TYDS": 40,
            "TTDS": 2,
            "RUYPA": 3.4,
            "PLAYS": 12,
            "Plays": 12,
            "PAATT\nTRGT": 2,
            "PACMP\nREC": 1,
            "PAYDS\nRCYDS": 6
        },
        "fpts": 16,
        "player": "Josh Jacobs"
    },
    {
        "player_id": 26054297,
        "fname": "Zack",
        "lname": "Moss",
        "team": "BUF",
        "team_id": 25,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 1,
            "RCTG": 2,
            "REC": 2,
            "RCLNG": 6,
            "RCYDS": 8,
            "RUYDS": 26,
            "RUTDS": 2,
            "RUATT": 8,
            "RULNG": 10,
            "DEFTD": 2,
            "PAFUM": 1,
            "PAFUML": 1,
            "FUML": 1,
            "FUM": 1,
            "FFPTS": 15.4,
            "FFPTS/G": 15.4,
            "TYDS": 34,
            "TTDS": 2,
            "RUYPA": 3.25,
            "PLAYS": 10,
            "Plays": 10,
            "PAATT\nTRGT": 2,
            "PACMP\nREC": 2,
            "PAYDS\nRCYDS": 8
        },
        "fpts": 15.4,
        "player": "Zack Moss"
    },
    {
        "player_id": 9521,
        "fname": "David",
        "lname": "Johnson",
        "team": "HOU",
        "team_id": 11,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 3,
            "RCTG": 6,
            "REC": 5,
            "RCLNG": 23,
            "RCYDS": 40,
            "RCTDS": 1,
            "RUYDS": 46,
            "RULNGTD": 1,
            "RUATT": 11,
            "RULNG": 20,
            "DEFTD": 1,
            "FFPTS": 14.6,
            "FFPTS/G": 4.9,
            "TYDS": 86,
            "TTDS": 1,
            "RUYPA": 4.181818181818182,
            "PLAYS": 17,
            "Plays": 17,
            "PAATT\nTRGT": 6,
            "PACMP\nREC": 5,
            "PAYDS\nRCYDS": 40,
            "PATDS\nRCTDS": 1
        },
        "fpts": 14.6,
        "player": "David Johnson"
    },
    {
        "player_id": 26055735,
        "fname": "JaMycal",
        "lname": "Hasty",
        "team": "SF",
        "team_id": 32,
        "position": "RB",
        "injured": 1,
        "injury_type": "Hasty is tending to a high-ankle sprain, and he will be out of commission for an undetermined length of time.",
        "stats": {
            "GMS": 2,
            "RCTG": 6,
            "REC": 5,
            "RCLNG": 23,
            "RCYDS": 36,
            "RUYDS": 41,
            "RUTDS": 1,
            "RUATT": 6,
            "RULNG": 24,
            "DEFTD": 1,
            "FFPTS": 13.7,
            "FFPTS/G": 6.8,
            "TYDS": 77,
            "TTDS": 1,
            "RUYPA": 6.833333333333333,
            "PLAYS": 12,
            "Plays": 12,
            "PAATT\nTRGT": 6,
            "PACMP\nREC": 5,
            "PAYDS\nRCYDS": 36
        },
        "fpts": 13.7,
        "player": "JaMycal Hasty"
    },
    {
        "player_id": 9425,
        "fname": "Mike",
        "lname": "Davis",
        "team": "ATL",
        "team_id": 12,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 13,
            "REC": 10,
            "RCLNG": 17,
            "RCYDS": 48,
            "RUYDS": 87,
            "RUATT": 24,
            "RULNG": 20,
            "FFPTS": 13.5,
            "FFPTS/G": 6.8,
            "TYDS": 135,
            "RUYPA": 3.625,
            "PLAYS": 37,
            "Plays": 37,
            "PAATT\nTRGT": 13,
            "PACMP\nREC": 10,
            "PAYDS\nRCYDS": 48
        },
        "fpts": 13.5,
        "player": "Mike Davis"
    },
    {
        "player_id": 11200,
        "fname": "Leonard",
        "lname": "Fournette",
        "team": "TB",
        "team_id": 20,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 1,
            "RCTG": 11,
            "REC": 9,
            "RCLNG": 26,
            "RCYDS": 51,
            "RUYDS": 84,
            "RUATT": 20,
            "RULNG": 17,
            "PAFUM": 1,
            "FUM": 1,
            "FFPTS": 13.5,
            "FFPTS/G": 6.8,
            "TYDS": 135,
            "RUYPA": 4.2,
            "PLAYS": 31,
            "Plays": 31,
            "PAATT\nTRGT": 11,
            "PACMP\nREC": 9,
            "PAYDS\nRCYDS": 51
        },
        "fpts": 13.5,
        "player": "Leonard Fournette"
    },
    {
        "player_id": 41303543,
        "fname": "Kenneth",
        "lname": "Gainwell",
        "team": "PHI",
        "team_id": 28,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RCTG": 6,
            "REC": 4,
            "RCLNG": 18,
            "RCYDS": 24,
            "RUYDS": 51,
            "RUTDS": 1,
            "RUATT": 15,
            "RULNG": 14,
            "DEFTD": 1,
            "FFPTS": 13.5,
            "FFPTS/G": 6.8,
            "TYDS": 75,
            "TTDS": 1,
            "RUYPA": 3.4,
            "PLAYS": 21,
            "Plays": 21,
            "PAATT\nTRGT": 6,
            "PACMP\nREC": 4,
            "PAYDS\nRCYDS": 24
        },
        "fpts": 13.5,
        "player": "Kenneth Gainwell"
    },
    {
        "player_id": 10450,
        "fname": "Kenyan",
        "lname": "Drake",
        "team": "LVR",
        "team_id": 10,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 1,
            "RCTG": 11,
            "REC": 10,
            "RCLNG": 34,
            "RCYDS": 105,
            "RUYDS": 20,
            "RUATT": 13,
            "RULNG": 11,
            "FFPTS": 12.5,
            "FFPTS/G": 6.2,
            "TYDS": 125,
            "RUYPA": 1.5384615384615385,
            "PLAYS": 24,
            "Plays": 24,
            "PAATT\nTRGT": 11,
            "PACMP\nREC": 10,
            "PAYDS\nRCYDS": 105
        },
        "fpts": 12.5,
        "player": "Kenyan Drake"
    },
    {
        "player_id": 58191,
        "fname": "Myles",
        "lname": "Gaskin",
        "team": "MIA",
        "team_id": 7,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 10,
            "REC": 9,
            "RCLNG": 23,
            "RCYDS": 48,
            "RUYDS": 74,
            "RUATT": 14,
            "RULNG": 33,
            "FFPTS": 12.2,
            "FFPTS/G": 6.1,
            "TYDS": 122,
            "RUYPA": 5.285714285714286,
            "PLAYS": 24,
            "Plays": 24,
            "PAATT\nTRGT": 10,
            "PACMP\nREC": 9,
            "PAYDS\nRCYDS": 48
        },
        "fpts": 12.2,
        "player": "Myles Gaskin"
    },
    {
        "player_id": 26054274,
        "fname": "Clyde",
        "lname": "Edwards-Helaire",
        "team": "KC",
        "team_id": 31,
        "position": "RB",
        "injured": 1,
        "injury_type": "Edwards-Helaire is ailing from an illness, and it remains to be seen if he will suit up for Sunday's clash with the Chargers.",
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 3,
            "REC": 3,
            "RCLNG": 14,
            "RCYDS": 29,
            "RUYDS": 89,
            "RUATT": 27,
            "RULNG": 18,
            "PAFUM": 1,
            "PAFUML": 1,
            "FUML": 1,
            "FUM": 1,
            "FFPTS": 11.8,
            "FFPTS/G": 5.9,
            "TYDS": 118,
            "RUYPA": 3.2962962962962963,
            "PLAYS": 30,
            "Plays": 30,
            "PAATT\nTRGT": 3,
            "PACMP\nREC": 3,
            "PAYDS\nRCYDS": 29
        },
        "fpts": 11.8,
        "player": "Clyde Edwards-Helaire"
    },
    {
        "player_id": 26056760,
        "fname": "James",
        "lname": "Robinson",
        "team": "JAC",
        "team_id": 13,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 9,
            "REC": 6,
            "RCLNG": 28,
            "RCYDS": 46,
            "RUYDS": 72,
            "RUATT": 16,
            "RULNG": 19,
            "PAFUM": 1,
            "FUM": 1,
            "FFPTS": 11.8,
            "FFPTS/G": 5.9,
            "TYDS": 118,
            "RUYPA": 4.5,
            "PLAYS": 25,
            "Plays": 25,
            "PAATT\nTRGT": 9,
            "PACMP\nREC": 6,
            "PAYDS\nRCYDS": 46
        },
        "fpts": 11.8,
        "player": "James Robinson"
    },
    {
        "player_id": 40204038,
        "fname": "Javonte",
        "lname": "Williams",
        "team": "DEN",
        "team_id": 8,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RCTG": 2,
            "REC": 2,
            "RCLNG": 6,
            "RCYDS": 6,
            "RUYDS": 109,
            "RUATT": 27,
            "RULNG": 28,
            "FFPTS": 11.5,
            "FFPTS/G": 5.8,
            "TYDS": 115,
            "RUYPA": 4.037037037037037,
            "PLAYS": 29,
            "Plays": 29,
            "PAATT\nTRGT": 2,
            "PACMP\nREC": 2,
            "PAYDS\nRCYDS": 6
        },
        "fpts": 11.5,
        "player": "Javonte Williams"
    },
    {
        "player_id": 39690300,
        "fname": "Michael",
        "lname": "Carter",
        "team": "NYJ",
        "team_id": 22,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RCTG": 5,
            "REC": 3,
            "RCLNG": 31,
            "RCYDS": 43,
            "RUYDS": 65,
            "RUATT": 15,
            "RULNG": 16,
            "FFPTS": 10.8,
            "FFPTS/G": 5.4,
            "TYDS": 108,
            "RUYPA": 4.333333333333333,
            "PLAYS": 20,
            "Plays": 20,
            "PAATT\nTRGT": 5,
            "PACMP\nREC": 3,
            "PAYDS\nRCYDS": 43
        },
        "fpts": 10.8,
        "player": "Michael Carter"
    },
    {
        "player_id": 12292,
        "fname": "Nyheim",
        "lname": "Hines",
        "team": "IND",
        "team_id": 19,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RCTG": 10,
            "REC": 7,
            "RCLNG": 29,
            "RCYDS": 65,
            "RUYDS": 39,
            "RUATT": 10,
            "RULNG": 13,
            "PRS": 7,
            "PRLNG": 7,
            "PRYDS": 1,
            "FFPTS": 10.4,
            "FFPTS/G": 5.2,
            "TYDS": 104,
            "RUYPA": 3.9,
            "PLAYS": 20,
            "Plays": 20,
            "PAATT\nTRGT": 10,
            "PACMP\nREC": 7,
            "PAYDS\nRCYDS": 65
        },
        "fpts": 10.4,
        "player": "Nyheim Hines"
    },
    {
        "player_id": 12092,
        "fname": "Saquon",
        "lname": "Barkley",
        "team": "NYG",
        "team_id": 17,
        "position": "RB",
        "injured": 1,
        "injury_type": "Barkley is expected to take the field against the Falcons on Sunday despite a knee injury.",
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 6,
            "REC": 3,
            "RCLNG": 9,
            "RCYDS": 13,
            "RUYDS": 83,
            "RUATT": 23,
            "RULNG": 46,
            "FFPTS": 9.6,
            "FFPTS/G": 4.8,
            "TYDS": 96,
            "RUYPA": 3.608695652173913,
            "PLAYS": 29,
            "Plays": 29,
            "PAATT\nTRGT": 6,
            "PACMP\nREC": 3,
            "PAYDS\nRCYDS": 13
        },
        "fpts": 9.6,
        "player": "Saquon Barkley"
    },
    {
        "player_id": 41119989,
        "fname": "Chuba",
        "lname": "Hubbard",
        "team": "CAR",
        "team_id": 15,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 3,
            "KRYDS": 21,
            "KRS": 1,
            "KRLNG": 21,
            "KRAVG": 21,
            "RCTG": 8,
            "REC": 5,
            "RCLNG": 13,
            "RCYDS": 31,
            "RUYDS": 62,
            "RUATT": 19,
            "RULNG": 23,
            "FFPTS": 9.3,
            "FFPTS/G": 3.1,
            "TYDS": 93,
            "RUYPA": 3.263157894736842,
            "PLAYS": 27,
            "Plays": 27,
            "PAATT\nTRGT": 8,
            "PACMP\nREC": 5,
            "PAYDS\nRCYDS": 31
        },
        "fpts": 9.3,
        "player": "Chuba Hubbard"
    },
    {
        "player_id": 11286,
        "fname": "James",
        "lname": "Conner",
        "team": "ARI",
        "team_id": 26,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RUYDS": 79,
            "RUATT": 24,
            "RULNG": 17,
            "FFPTS": 7.9,
            "FFPTS/G": 4,
            "TYDS": 79,
            "RUYPA": 3.2916666666666665,
            "PLAYS": 24,
            "Plays": 24
        },
        "fpts": 7.9,
        "player": "James Conner"
    },
    {
        "player_id": 57239,
        "fname": "Ty",
        "lname": "Johnson",
        "team": "NYJ",
        "team_id": 22,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 1,
            "RCTG": 3,
            "REC": 1,
            "RCLNG": 11,
            "RCYDS": 11,
            "RUYDS": 65,
            "RUATT": 16,
            "RULNG": 29,
            "AST": 1,
            "FFPTS": 7.6,
            "FFPTS/G": 3.8,
            "TYDS": 76,
            "RUYPA": 4.0625,
            "PLAYS": 19,
            "Plays": 19,
            "PAATT\nTRGT": 3,
            "PACMP\nREC": 1,
            "PAYDS\nRCYDS": 11
        },
        "fpts": 7.6,
        "player": "Ty Johnson"
    },
    {
        "player_id": 8661,
        "fname": "Carlos",
        "lname": "Hyde",
        "team": "JAC",
        "team_id": 13,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RCTG": 4,
            "REC": 2,
            "RCLNG": 9,
            "RCYDS": 14,
            "RUYDS": 51,
            "RUATT": 11,
            "RULNG": 19,
            "FFPTS": 6.5,
            "FFPTS/G": 3.2,
            "TYDS": 65,
            "RUYPA": 4.636363636363637,
            "PLAYS": 15,
            "Plays": 15,
            "PAATT\nTRGT": 4,
            "PACMP\nREC": 2,
            "PAYDS\nRCYDS": 14
        },
        "fpts": 6.5,
        "player": "Carlos Hyde"
    },
    {
        "player_id": 11408,
        "fname": "Jeremy",
        "lname": "McNichols",
        "team": "TEN",
        "team_id": 30,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RCTG": 7,
            "REC": 6,
            "RCLNG": 21,
            "RCYDS": 50,
            "RUYDS": 12,
            "RUATT": 3,
            "RULNG": 11,
            "FFPTS": 6.2,
            "FFPTS/G": 3.1,
            "TYDS": 62,
            "RUYPA": 4,
            "PLAYS": 10,
            "Plays": 10,
            "PAATT\nTRGT": 7,
            "PACMP\nREC": 6,
            "PAYDS\nRCYDS": 50
        },
        "fpts": 6.2,
        "player": "Jeremy McNichols"
    },
    {
        "player_id": 12613,
        "fname": "Darrel",
        "lname": "Williams",
        "team": "KC",
        "team_id": 31,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RUYDS": 2,
            "RUTDS": 1,
            "RUATT": 4,
            "RULNG": 6,
            "DEFTD": 1,
            "FFPTS": 6.2,
            "FFPTS/G": 3.1,
            "TYDS": 2,
            "TTDS": 1,
            "RUYPA": 0.5,
            "PLAYS": 4,
            "Plays": 4
        },
        "fpts": 6.2,
        "player": "Darrel Williams"
    },
    {
        "player_id": 10477,
        "fname": "Andy",
        "lname": "Janovich",
        "team": "CLE",
        "team_id": 29,
        "position": "FB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 1,
            "RUTDS": 1,
            "RUATT": 2,
            "RULNG": 1,
            "DEFTD": 1,
            "FFPTS": 6,
            "FFPTS/G": 3,
            "TTDS": 1,
            "PLAYS": 3,
            "Plays": 3,
            "PAATT\nTRGT": 1
        },
        "fpts": 6,
        "player": "Andy Janovich"
    },
    {
        "player_id": 26138374,
        "fname": "Tony",
        "lname": "Jones Jr.",
        "team": "NO",
        "team_id": 5,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 1,
            "RCTG": 1,
            "REC": 1,
            "RCLNG": 3,
            "RCYDS": 3,
            "RUYDS": 57,
            "RUATT": 14,
            "RULNG": 15,
            "FFPTS": 6,
            "FFPTS/G": 3,
            "TYDS": 60,
            "RUYPA": 4.071428571428571,
            "PLAYS": 15,
            "Plays": 15,
            "PAATT\nTRGT": 1,
            "PACMP\nREC": 1,
            "PAYDS\nRCYDS": 3
        },
        "fpts": 6,
        "player": "Tony Jones Jr."
    },
    {
        "player_id": 26055254,
        "fname": "AJ",
        "lname": "Dillon",
        "team": "GB",
        "team_id": 14,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RCTG": 3,
            "REC": 2,
            "RCLNG": 15,
            "RCYDS": 15,
            "RUYDS": 37,
            "RUATT": 9,
            "RULNG": 14,
            "FFPTS": 5.2,
            "FFPTS/G": 2.6,
            "TYDS": 52,
            "RUYPA": 4.111111111111111,
            "PLAYS": 12,
            "Plays": 12,
            "PAATT\nTRGT": 3,
            "PACMP\nREC": 2,
            "PAYDS\nRCYDS": 15
        },
        "fpts": 5.2,
        "player": "AJ Dillon"
    },
    {
        "player_id": 12278,
        "fname": "Ronald",
        "lname": "Jones",
        "team": "TB",
        "team_id": 20,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 1,
            "RCTG": 3,
            "REC": 1,
            "RCLNG": 9,
            "RCYDS": 9,
            "RUYDS": 41,
            "RUATT": 10,
            "RULNG": 15,
            "PAFUM": 1,
            "PAFUML": 1,
            "FUML": 1,
            "FUM": 1,
            "FFPTS": 5,
            "FFPTS/G": 2.5,
            "TYDS": 50,
            "RUYPA": 4.1,
            "PLAYS": 13,
            "Plays": 13,
            "PAATT\nTRGT": 3,
            "PACMP\nREC": 1,
            "PAYDS\nRCYDS": 9
        },
        "fpts": 5,
        "player": "Ronald Jones"
    },
    {
        "player_id": 9788,
        "fname": "Tevin",
        "lname": "Coleman",
        "team": "NYJ",
        "team_id": 22,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 1,
            "RUYDS": 48,
            "RUATT": 14,
            "RULNG": 26,
            "FFPTS": 4.8,
            "FFPTS/G": 2.4,
            "TYDS": 48,
            "RUYPA": 3.4285714285714284,
            "PLAYS": 14,
            "Plays": 14
        },
        "fpts": 4.8,
        "player": "Tevin Coleman"
    },
    {
        "player_id": 12111,
        "fname": "Sony",
        "lname": "Michel",
        "team": "LAR",
        "team_id": 9,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RUYDS": 48,
            "RUATT": 11,
            "RULNG": 13,
            "FFPTS": 4.8,
            "FFPTS/G": 2.4,
            "TYDS": 48,
            "RUYPA": 4.363636363636363,
            "PLAYS": 11,
            "Plays": 11
        },
        "fpts": 4.8,
        "player": "Sony Michel"
    },
    {
        "player_id": 26446529,
        "fname": "Salvon",
        "lname": "Ahmed",
        "team": "MIA",
        "team_id": 7,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RCTG": 6,
            "REC": 2,
            "RCLNG": 18,
            "RCYDS": 24,
            "RUYDS": 21,
            "RUATT": 9,
            "RULNG": 16,
            "FFPTS": 4.5,
            "FFPTS/G": 2.2,
            "TYDS": 45,
            "RUYPA": 2.3333333333333335,
            "PLAYS": 15,
            "Plays": 15,
            "PAATT\nTRGT": 6,
            "PACMP\nREC": 2,
            "PAYDS\nRCYDS": 24
        },
        "fpts": 4.5,
        "player": "Salvon Ahmed"
    },
    {
        "player_id": 9167,
        "fname": "Damien",
        "lname": "Williams",
        "team": "CHI",
        "team_id": 27,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RCTG": 8,
            "REC": 6,
            "RCLNG": 14,
            "RCYDS": 26,
            "RUYDS": 18,
            "RUATT": 8,
            "RULNG": 12,
            "FFPTS": 4.4,
            "FFPTS/G": 2.2,
            "TYDS": 44,
            "RUYPA": 2.25,
            "PLAYS": 16,
            "Plays": 16,
            "PAATT\nTRGT": 8,
            "PACMP\nREC": 6,
            "PAYDS\nRCYDS": 26
        },
        "fpts": 4.4,
        "player": "Damien Williams"
    },
    {
        "player_id": 9684,
        "fname": "Malcolm",
        "lname": "Brown",
        "team": "MIA",
        "team_id": 7,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RUYDS": 37,
            "RUATT": 10,
            "RULNG": 17,
            "FFPTS": 3.7,
            "FFPTS/G": 1.9,
            "TYDS": 37,
            "RUYPA": 3.7,
            "PLAYS": 10,
            "Plays": 10
        },
        "fpts": 3.7,
        "player": "Malcolm Brown"
    },
    {
        "player_id": 12240,
        "fname": "Justin",
        "lname": "Jackson",
        "team": "LAC",
        "team_id": 3,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RCTG": 2,
            "REC": 2,
            "RCLNG": 10,
            "RCYDS": 10,
            "RUYDS": 26,
            "RUATT": 5,
            "RULNG": 12,
            "AST": 1,
            "FFPTS": 3.6,
            "FFPTS/G": 1.8,
            "TYDS": 36,
            "RUYPA": 5.2,
            "PLAYS": 7,
            "Plays": 7,
            "PAATT\nTRGT": 2,
            "PACMP\nREC": 2,
            "PAYDS\nRCYDS": 10
        },
        "fpts": 3.6,
        "player": "Justin Jackson"
    },
    {
        "player_id": 9091,
        "fname": "Keith",
        "lname": "Smith",
        "team": "ATL",
        "team_id": 12,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 1,
            "RCTG": 4,
            "REC": 3,
            "RCLNG": 9,
            "RCYDS": 18,
            "RUYDS": 16,
            "RUATT": 4,
            "RULNG": 11,
            "AST": 2,
            "FFPTS": 3.4,
            "FFPTS/G": 1.7,
            "TYDS": 34,
            "RUYPA": 4,
            "PLAYS": 8,
            "Plays": 8,
            "PAATT\nTRGT": 4,
            "PACMP\nREC": 3,
            "PAYDS\nRCYDS": 18
        },
        "fpts": 3.4,
        "player": "Keith Smith"
    },
    {
        "player_id": 58174,
        "fname": "Alexander",
        "lname": "Mattison",
        "team": "MIN",
        "team_id": 16,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RCTG": 2,
            "REC": 2,
            "RCLNG": 21,
            "RCYDS": 21,
            "RUYDS": 13,
            "RUATT": 4,
            "RULNG": 8,
            "FFPTS": 3.4,
            "FFPTS/G": 1.7,
            "TYDS": 34,
            "RUYPA": 3.25,
            "PLAYS": 6,
            "Plays": 6,
            "PAATT\nTRGT": 2,
            "PACMP\nREC": 2,
            "PAYDS\nRCYDS": 21
        },
        "fpts": 3.4,
        "player": "Alexander Mattison"
    },
    {
        "player_id": 10990,
        "fname": "Peyton",
        "lname": "Barber",
        "team": "LVR",
        "team_id": 10,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 1,
            "RUYDS": 32,
            "RUATT": 13,
            "RULNG": 13,
            "FFPTS": 3.2,
            "FFPTS/G": 3.2,
            "TYDS": 32,
            "RUYPA": 2.4615384615384617,
            "PLAYS": 13,
            "Plays": 13
        },
        "fpts": 3.2,
        "player": "Peyton Barber"
    },
    {
        "player_id": 8777,
        "fname": "Devonta",
        "lname": "Freeman",
        "team": "BAL",
        "team_id": 24,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 1,
            "RUYDS": 29,
            "RUATT": 2,
            "RULNG": 31,
            "FFPTS": 2.9,
            "FFPTS/G": 2.9,
            "TYDS": 29,
            "RUYPA": 14.5,
            "PLAYS": 2,
            "Plays": 2
        },
        "fpts": 2.9,
        "player": "Devonta Freeman"
    },
    {
        "player_id": 11370,
        "fname": "Samaje",
        "lname": "Perine",
        "team": "CIN",
        "team_id": 23,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RCTG": 2,
            "REC": 1,
            "RCLNG": 7,
            "RCYDS": 7,
            "RUYDS": 22,
            "RUATT": 5,
            "RULNG": 13,
            "FFPTS": 2.9,
            "FFPTS/G": 1.4,
            "TYDS": 29,
            "RUYPA": 4.4,
            "PLAYS": 7,
            "Plays": 7,
            "PAATT\nTRGT": 2,
            "PACMP\nREC": 1,
            "PAYDS\nRCYDS": 7
        },
        "fpts": 2.9,
        "player": "Samaje Perine"
    },
    {
        "player_id": 8246,
        "fname": "Giovani",
        "lname": "Bernard",
        "team": "TB",
        "team_id": 20,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "KRYDS": 16,
            "KRS": 1,
            "KRLNG": 16,
            "KRAVG": 16,
            "RCTG": 5,
            "REC": 4,
            "RCLNG": 18,
            "RCYDS": 28,
            "FFPTS": 2.8,
            "FFPTS/G": 1.4,
            "TYDS": 28,
            "PLAYS": 5,
            "Plays": 5,
            "PAATT\nTRGT": 5,
            "PACMP\nREC": 4,
            "PAYDS\nRCYDS": 28
        },
        "fpts": 2.8,
        "player": "Giovani Bernard"
    },
    {
        "player_id": 10515,
        "fname": "Alex",
        "lname": "Collins",
        "team": "SEA",
        "team_id": 21,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 1,
            "RUYDS": 25,
            "RUATT": 1,
            "RULNG": 25,
            "FFPTS": 2.5,
            "FFPTS/G": 2.5,
            "TYDS": 25,
            "RUYPA": 25,
            "PLAYS": 1,
            "Plays": 1
        },
        "fpts": 2.5,
        "player": "Alex Collins"
    },
    {
        "player_id": 12153,
        "fname": "Royce",
        "lname": "Freeman",
        "team": "CAR",
        "team_id": 15,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 3,
            "RCTG": 1,
            "REC": 1,
            "RCLNG": 8,
            "RCYDS": 8,
            "RUYDS": 17,
            "RUATT": 5,
            "RULNG": 13,
            "FFPTS": 2.5,
            "FFPTS/G": 0.8,
            "TYDS": 25,
            "RUYPA": 3.4,
            "PLAYS": 6,
            "Plays": 6,
            "PAATT\nTRGT": 1,
            "PACMP\nREC": 1,
            "PAYDS\nRCYDS": 8
        },
        "fpts": 2.5,
        "player": "Royce Freeman"
    },
    {
        "player_id": 7963,
        "fname": "Kyle",
        "lname": "Juszczyk",
        "team": "SF",
        "team_id": 32,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "RCTG": 4,
            "REC": 3,
            "RCLNG": 15,
            "RCYDS": 22,
            "RUYDS": 2,
            "RUATT": 1,
            "RULNG": 2,
            "FFPTS": 2.4,
            "FFPTS/G": 1.2,
            "TYDS": 24,
            "RUYPA": 2,
            "PLAYS": 5,
            "Plays": 5,
            "PAATT\nTRGT": 4,
            "PACMP\nREC": 3,
            "PAYDS\nRCYDS": 22
        },
        "fpts": 2.4,
        "player": "Kyle Juszczyk"
    },
    {
        "player_id": 10475,
        "fname": "Devontae",
        "lname": "Booker",
        "team": "NYG",
        "team_id": 17,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RCTG": 2,
            "REC": 2,
            "RCLNG": 8,
            "RCYDS": 8,
            "RUYDS": 16,
            "RUATT": 6,
            "RULNG": 13,
            "FFPTS": 2.4,
            "FFPTS/G": 1.2,
            "TYDS": 24,
            "RUYPA": 2.6666666666666665,
            "PLAYS": 8,
            "Plays": 8,
            "PAATT\nTRGT": 2,
            "PACMP\nREC": 2,
            "PAYDS\nRCYDS": 8
        },
        "fpts": 2.4,
        "player": "Devontae Booker"
    },
    {
        "player_id": 56035,
        "fname": "Alec",
        "lname": "Ingold",
        "team": "LVR",
        "team_id": 10,
        "position": "RB",
        "injured": 1,
        "injury_type": "Ingold is projected to face the Dolphins on Sunday despite a fibula injury.",
        "stats": {
            "GMS": 2,
            "GMST": 1,
            "RCTG": 5,
            "REC": 4,
            "RCLNG": 9,
            "RCYDS": 22,
            "FFPTS": 2.2,
            "FFPTS/G": 1.1,
            "TYDS": 22,
            "PLAYS": 5,
            "Plays": 5,
            "PAATT\nTRGT": 5,
            "PACMP\nREC": 4,
            "PAYDS\nRCYDS": 22
        },
        "fpts": 2.2,
        "player": "Alec Ingold"
    },
    {
        "player_id": 36012349,
        "fname": "Kylin",
        "lname": "Hill",
        "team": "GB",
        "team_id": 14,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "KRYDS": 89,
            "KRS": 4,
            "KRLNG": 58,
            "KRAVG": 44.5,
            "RUYDS": 22,
            "RUATT": 7,
            "RULNG": 13,
            "FFPTS": 2.2,
            "FFPTS/G": 1.1,
            "TYDS": 22,
            "RUYPA": 3.142857142857143,
            "PLAYS": 7,
            "Plays": 7
        },
        "fpts": 2.2,
        "player": "Kylin Hill"
    },
    {
        "player_id": 9725,
        "fname": "Raheem",
        "lname": "Mostert",
        "team": "SF",
        "team_id": 32,
        "position": "RB",
        "injured": 1,
        "injury_type": "Mostert has been shuttled to the injured reserve list after undergoing season-ending knee surgery.",
        "stats": {
            "GMS": 1,
            "GMST": 1,
            "RUYDS": 20,
            "RUATT": 2,
            "RULNG": 11,
            "FFPTS": 2,
            "FFPTS/G": 2,
            "TYDS": 20,
            "RUYPA": 10,
            "PLAYS": 2,
            "Plays": 2
        },
        "fpts": 2,
        "player": "Raheem Mostert"
    },
    {
        "player_id": 9906,
        "fname": "Ameer",
        "lname": "Abdullah",
        "team": "MIN",
        "team_id": 16,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RCTG": 3,
            "REC": 2,
            "RCLNG": 10,
            "RCYDS": 15,
            "RUYDS": 4,
            "RUATT": 1,
            "RULNG": 4,
            "FFPTS": 1.9,
            "FFPTS/G": 0.9,
            "TYDS": 19,
            "RUYPA": 4,
            "PLAYS": 4,
            "Plays": 4,
            "PAATT\nTRGT": 3,
            "PACMP\nREC": 2,
            "PAYDS\nRCYDS": 15
        },
        "fpts": 1.9,
        "player": "Ameer Abdullah"
    },
    {
        "player_id": 11686,
        "fname": "Patrick",
        "lname": "Ricard",
        "team": "BAL",
        "team_id": 24,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 1,
            "RCTG": 3,
            "REC": 2,
            "RCLNG": 9,
            "RCYDS": 15,
            "RUYDS": 2,
            "RUATT": 1,
            "RULNG": 2,
            "FFPTS": 1.7,
            "FFPTS/G": 0.8,
            "TYDS": 17,
            "RUYPA": 2,
            "PLAYS": 4,
            "Plays": 4,
            "PAATT\nTRGT": 3,
            "PACMP\nREC": 2,
            "PAYDS\nRCYDS": 15
        },
        "fpts": 1.7,
        "player": "Patrick Ricard"
    },
    {
        "player_id": 11416,
        "fname": "Marlon",
        "lname": "Mack",
        "team": "IND",
        "team_id": 19,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 1,
            "RCTG": 1,
            "RUYDS": 16,
            "RUATT": 5,
            "RULNG": 6,
            "FFPTS": 1.6,
            "FFPTS/G": 1.6,
            "TYDS": 16,
            "RUYPA": 3.2,
            "PLAYS": 6,
            "Plays": 6,
            "PAATT\nTRGT": 1
        },
        "fpts": 1.6,
        "player": "Marlon Mack"
    },
    {
        "player_id": 8665,
        "fname": "Jerick",
        "lname": "McKinnon",
        "team": "KC",
        "team_id": 31,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RCTG": 1,
            "REC": 1,
            "RCLNG": 14,
            "RCYDS": 14,
            "FFPTS": 1.4,
            "FFPTS/G": 0.7,
            "TYDS": 14,
            "PLAYS": 1,
            "Plays": 1,
            "PAATT\nTRGT": 1,
            "PACMP\nREC": 1,
            "PAYDS\nRCYDS": 14
        },
        "fpts": 1.4,
        "player": "Jerick McKinnon"
    },
    {
        "player_id": 57064,
        "fname": "Travis",
        "lname": "Homer",
        "team": "SEA",
        "team_id": 21,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RCTG": 2,
            "REC": 2,
            "RCLNG": 11,
            "RCYDS": 14,
            "AST": 1,
            "FFPTS": 1.4,
            "FFPTS/G": 0.7,
            "TYDS": 14,
            "PLAYS": 2,
            "Plays": 2,
            "PAATT\nTRGT": 2,
            "PACMP\nREC": 2,
            "PAYDS\nRCYDS": 14
        },
        "fpts": 1.4,
        "player": "Travis Homer"
    },
    {
        "player_id": 41589319,
        "fname": "Chris",
        "lname": "Evans",
        "team": "CIN",
        "team_id": 23,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RCTG": 1,
            "REC": 1,
            "RCLNG": 14,
            "RCYDS": 14,
            "FFPTS": 1.4,
            "FFPTS/G": 0.7,
            "TYDS": 14,
            "PLAYS": 1,
            "Plays": 1,
            "PAATT\nTRGT": 1,
            "PACMP\nREC": 1,
            "PAYDS\nRCYDS": 14
        },
        "fpts": 1.4,
        "player": "Chris Evans"
    },
    {
        "player_id": 9910,
        "fname": "Michael",
        "lname": "Burton",
        "team": "KC",
        "team_id": 31,
        "position": "FB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "KRYDS": 9,
            "KRS": 1,
            "KRLNG": 9,
            "KRAVG": 9,
            "RCTG": 1,
            "REC": 1,
            "RCLNG": 11,
            "RCYDS": 11,
            "RUYDS": 2,
            "RUATT": 1,
            "RULNG": 2,
            "FFPTS": 1.3,
            "FFPTS/G": 0.7,
            "TYDS": 13,
            "RUYPA": 2,
            "PLAYS": 2,
            "Plays": 2,
            "PAATT\nTRGT": 1,
            "PACMP\nREC": 1,
            "PAYDS\nRCYDS": 11
        },
        "fpts": 1.3,
        "player": "Michael Burton"
    },
    {
        "player_id": 8126,
        "fname": "Rex",
        "lname": "Burkhead",
        "team": "HOU",
        "team_id": 11,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 3,
            "RCTG": 3,
            "REC": 2,
            "RCLNG": 11,
            "RCYDS": 11,
            "FFPTS": 1.1,
            "FFPTS/G": 0.4,
            "TYDS": 11,
            "PLAYS": 3,
            "Plays": 3,
            "PAATT\nTRGT": 3,
            "PACMP\nREC": 2,
            "PAYDS\nRCYDS": 11
        },
        "fpts": 1.1,
        "player": "Rex Burkhead"
    },
    {
        "player_id": 40549638,
        "fname": "Rhamondre",
        "lname": "Stevenson",
        "team": "NE",
        "team_id": 1,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 1,
            "RCTG": 1,
            "REC": 1,
            "RCLNG": 9,
            "RCYDS": 9,
            "RUYDS": 2,
            "RUATT": 1,
            "RULNG": 2,
            "PAFUM": 1,
            "PAFUML": 1,
            "FUML": 1,
            "FUM": 1,
            "FFPTS": 1.1,
            "FFPTS/G": 1.1,
            "TYDS": 11,
            "RUYPA": 2,
            "PLAYS": 2,
            "Plays": 2,
            "PAATT\nTRGT": 1,
            "PACMP\nREC": 1,
            "PAYDS\nRCYDS": 9
        },
        "fpts": 1.1,
        "player": "Rhamondre Stevenson"
    },
    {
        "player_id": 26054203,
        "fname": "DeeJay",
        "lname": "Dallas",
        "team": "SEA",
        "team_id": 21,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "KRYDS": 52,
            "KRS": 4,
            "KRLNG": 40,
            "KRAVG": 32,
            "RCTG": 1,
            "REC": 1,
            "RCLNG": 5,
            "RCYDS": 5,
            "RUYDS": 5,
            "RUATT": 1,
            "RULNG": 5,
            "AST": 1,
            "FFPTS": 1,
            "FFPTS/G": 0.5,
            "TYDS": 10,
            "RUYPA": 5,
            "PLAYS": 2,
            "Plays": 2,
            "PAATT\nTRGT": 1,
            "PACMP\nREC": 1,
            "PAYDS\nRCYDS": 5
        },
        "fpts": 1,
        "player": "DeeJay Dallas"
    },
    {
        "player_id": 11133,
        "fname": "C.J.",
        "lname": "Ham",
        "team": "MIN",
        "team_id": 16,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 1,
            "RCTG": 2,
            "REC": 2,
            "RCLNG": 6,
            "RCYDS": 9,
            "FFPTS": 0.9,
            "FFPTS/G": 0.5,
            "TYDS": 9,
            "PLAYS": 2,
            "Plays": 2,
            "PAATT\nTRGT": 2,
            "PACMP\nREC": 2,
            "PAYDS\nRCYDS": 9
        },
        "fpts": 0.9,
        "player": "C.J. Ham"
    },
    {
        "player_id": 40041627,
        "fname": "Jaret",
        "lname": "Patterson",
        "team": "WAS",
        "team_id": 4,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RUYDS": 9,
            "RUATT": 2,
            "RULNG": 5,
            "FFPTS": 0.9,
            "FFPTS/G": 0.5,
            "TYDS": 9,
            "RUYPA": 4.5,
            "PLAYS": 2,
            "Plays": 2
        },
        "fpts": 0.9,
        "player": "Jaret Patterson"
    },
    {
        "player_id": 10191,
        "fname": "Ty",
        "lname": "Montgomery",
        "team": "NO",
        "team_id": 5,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 1,
            "RCTG": 2,
            "REC": 2,
            "RCLNG": 8,
            "RCYDS": 8,
            "AST": 2,
            "FFPTS": 0.8,
            "FFPTS/G": 0.4,
            "TYDS": 8,
            "PLAYS": 2,
            "Plays": 2,
            "PAATT\nTRGT": 2,
            "PACMP\nREC": 2,
            "PAYDS\nRCYDS": 8
        },
        "fpts": 0.8,
        "player": "Ty Montgomery"
    },
    {
        "player_id": 12096,
        "fname": "Rashaad",
        "lname": "Penny",
        "team": "SEA",
        "team_id": 21,
        "position": "RB",
        "injured": 1,
        "injury_type": "Penny missed the previous game with a calf strain, and he will not face the Vikings on Sunday.",
        "stats": {
            "GMS": 1,
            "RUYDS": 8,
            "RUATT": 2,
            "RULNG": 4,
            "FFPTS": 0.8,
            "FFPTS/G": 0.8,
            "TYDS": 8,
            "RUYPA": 4,
            "PLAYS": 2,
            "Plays": 2
        },
        "fpts": 0.8,
        "player": "Rashaad Penny"
    },
    {
        "player_id": 39446778,
        "fname": "Trey",
        "lname": "Sermon",
        "team": "SF",
        "team_id": 32,
        "position": "RB",
        "injured": 1,
        "injury_type": "Sermon exited the previous contest with a concussion, and his status for Sunday's game versus the Packers is unknown.",
        "stats": {
            "GMS": 1,
            "RUYDS": 8,
            "RUATT": 1,
            "RULNG": 8,
            "FFPTS": 0.8,
            "FFPTS/G": 0.8,
            "TYDS": 8,
            "RUYPA": 8,
            "PLAYS": 1,
            "Plays": 1
        },
        "fpts": 0.8,
        "player": "Trey Sermon"
    },
    {
        "player_id": 41589324,
        "fname": "Gary",
        "lname": "Brightwell",
        "team": "NYG",
        "team_id": 17,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RCTG": 1,
            "REC": 1,
            "RCLNG": 6,
            "RCYDS": 6,
            "FFPTS": 0.6,
            "FFPTS/G": 0.3,
            "TYDS": 6,
            "PLAYS": 1,
            "Plays": 1,
            "PAATT\nTRGT": 1,
            "PACMP\nREC": 1,
            "PAYDS\nRCYDS": 6
        },
        "fpts": 0.6,
        "player": "Gary Brightwell"
    },
    {
        "player_id": 5995,
        "fname": "Brandon",
        "lname": "Bolden",
        "team": "NE",
        "team_id": 1,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "KRYDS": 23,
            "KRS": 1,
            "KRLNG": 23,
            "KRAVG": 23,
            "RUYDS": 5,
            "RUATT": 1,
            "RULNG": 5,
            "FFPTS": 0.5,
            "FFPTS/G": 0.2,
            "TYDS": 5,
            "RUYPA": 5,
            "PLAYS": 1,
            "Plays": 1
        },
        "fpts": 0.5,
        "player": "Brandon Bolden"
    },
    {
        "player_id": 11078,
        "fname": "Elijhaa",
        "lname": "Penny",
        "team": "NYG",
        "team_id": 17,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 1,
            "RCTG": 1,
            "RUYDS": 5,
            "RUATT": 2,
            "RULNG": 3,
            "FFPTS": 0.5,
            "FFPTS/G": 0.2,
            "TYDS": 5,
            "RUYPA": 2.5,
            "PLAYS": 3,
            "Plays": 3,
            "PAATT\nTRGT": 1
        },
        "fpts": 0.5,
        "player": "Elijhaa Penny"
    },
    {
        "player_id": 11650,
        "fname": "Matt",
        "lname": "Breida",
        "team": "BUF",
        "team_id": 25,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RUYDS": 4,
            "RUATT": 4,
            "RULNG": 7,
            "FFPTS": 0.4,
            "FFPTS/G": 0.2,
            "TYDS": 4,
            "RUYPA": 1,
            "PLAYS": 4,
            "Plays": 4
        },
        "fpts": 0.4,
        "player": "Matt Breida"
    },
    {
        "player_id": 12234,
        "fname": "Trenton",
        "lname": "Cannon",
        "team": "SF",
        "team_id": 32,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "KRYDS": 11,
            "KRS": 1,
            "KRLNG": 11,
            "KRAVG": 11,
            "RUYDS": 4,
            "RUATT": 3,
            "RULNG": 2,
            "FFPTS": 0.4,
            "FFPTS/G": 0.2,
            "TYDS": 4,
            "RUYPA": 1.3333333333333333,
            "PLAYS": 3,
            "Plays": 3
        },
        "fpts": 0.4,
        "player": "Trenton Cannon"
    },
    {
        "player_id": 27070125,
        "fname": "J.J.",
        "lname": "Taylor",
        "team": "NE",
        "team_id": 1,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 1,
            "RUYDS": 3,
            "RUATT": 2,
            "RULNG": 2,
            "FFPTS": 0.3,
            "FFPTS/G": 0.3,
            "TYDS": 3,
            "RUYPA": 1.5,
            "PLAYS": 2,
            "Plays": 2
        },
        "fpts": 0.3,
        "player": "J.J. Taylor"
    },
    {
        "player_id": 26317414,
        "fname": "Gabe",
        "lname": "Nabers",
        "team": "LAC",
        "team_id": 3,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RUYDS": 2,
            "RUATT": 1,
            "RULNG": 2,
            "AST": 1,
            "FFPTS": 0.2,
            "FFPTS/G": 0.1,
            "TYDS": 2,
            "RUYPA": 2,
            "PLAYS": 1,
            "Plays": 1
        },
        "fpts": 0.2,
        "player": "Gabe Nabers"
    },
    {
        "player_id": 27717695,
        "fname": "Reggie",
        "lname": "Gilliam",
        "team": "BUF",
        "team_id": 25,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RUYDS": 2,
            "RUATT": 2,
            "RULNG": 2,
            "FFPTS": 0.2,
            "FFPTS/G": 0.1,
            "TYDS": 2,
            "RUYPA": 1,
            "PLAYS": 2,
            "Plays": 2
        },
        "fpts": 0.2,
        "player": "Reggie Gilliam"
    },
    {
        "player_id": 42127489,
        "fname": "Mekhi",
        "lname": "Sargent",
        "team": "TEN",
        "team_id": 30,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RUYDS": 2,
            "RUATT": 1,
            "RULNG": 2,
            "FFPTS": 0.2,
            "FFPTS/G": 0.1,
            "TYDS": 2,
            "RUYPA": 2,
            "PLAYS": 1,
            "Plays": 1
        },
        "fpts": 0.2,
        "player": "Mekhi Sargent"
    },
    {
        "player_id": 58071,
        "fname": "Benny",
        "lname": "Snell Jr.",
        "team": "PIT",
        "team_id": 18,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "RUYDS": 1,
            "RUATT": 2,
            "RULNG": 1,
            "AST": 1,
            "FFPTS": 0.1,
            "FFPTS/G": 0.1,
            "TYDS": 1,
            "RUYPA": 0.5,
            "PLAYS": 2,
            "Plays": 2
        },
        "fpts": 0.1,
        "player": "Benny Snell Jr."
    },
    {
        "player_id": 4962,
        "fname": "Taiwan",
        "lname": "Jones",
        "team": "BUF",
        "team_id": 25,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "FFPTS": 0
        },
        "fpts": 0,
        "player": "Taiwan Jones"
    },
    {
        "player_id": 5275,
        "fname": "Nick",
        "lname": "Bellore",
        "team": "SEA",
        "team_id": 21,
        "position": "FB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "AST": 2,
            "FFPTS": 0
        },
        "fpts": 0,
        "player": "Nick Bellore"
    },
    {
        "player_id": 6255,
        "fname": "Josh",
        "lname": "Harris",
        "team": "ATL",
        "team_id": 12,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "AST": 3,
            "FFPTS": 0
        },
        "fpts": 0,
        "player": "Josh Harris"
    },
    {
        "player_id": 10441,
        "fname": "Austin",
        "lname": "Johnson",
        "team": "NYG",
        "team_id": 17,
        "position": "FB",
        "injured": 1,
        "injury_type": "Johnson is ailing from an illness, and it is unknown if he will partake in Sunday's showdown with the Falcons.",
        "stats": {
            "GMS": 2,
            "GMST": 2,
            "TKL": 9,
            "SCK": 1,
            "SOLO": 5,
            "AST": 4,
            "FFPTS": 0
        },
        "fpts": 0,
        "player": "Austin Johnson"
    },
    {
        "player_id": 10534,
        "fname": "Derek",
        "lname": "Watt",
        "team": "PIT",
        "team_id": 18,
        "position": "FB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "FFPTS": 0
        },
        "fpts": 0,
        "player": "Derek Watt"
    },
    {
        "player_id": 10552,
        "fname": "Dwayne",
        "lname": "Washington",
        "team": "NO",
        "team_id": 5,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "AST": 1,
            "FFPTS": 0
        },
        "fpts": 0,
        "player": "Dwayne Washington"
    },
    {
        "player_id": 11319,
        "fname": "Alex",
        "lname": "Armah",
        "team": "NO",
        "team_id": 5,
        "position": "FB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 1,
            "KRYDS": 17,
            "KRS": 1,
            "KRLNG": 17,
            "KRAVG": 17,
            "FFPTS": 0
        },
        "fpts": 0,
        "player": "Alex Armah"
    },
    {
        "player_id": 11481,
        "fname": "Dare",
        "lname": "Ogunbowale",
        "team": "JAC",
        "team_id": 13,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "FFPTS": 0
        },
        "fpts": 0,
        "player": "Dare Ogunbowale"
    },
    {
        "player_id": 11996,
        "fname": "Corey",
        "lname": "Clement",
        "team": "DAL",
        "team_id": 6,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "FFPTS": 0
        },
        "fpts": 0,
        "player": "Corey Clement"
    },
    {
        "player_id": 12180,
        "fname": "Boston",
        "lname": "Scott",
        "team": "PHI",
        "team_id": 28,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "AST": 1,
            "FFPTS": 0
        },
        "fpts": 0,
        "player": "Boston Scott"
    },
    {
        "player_id": 12282,
        "fname": "Marcus",
        "lname": "Allen",
        "team": "PIT",
        "team_id": 18,
        "position": "RB",
        "injured": 1,
        "injury_type": "Allen is hampered by an abdominal issue, and it remains to be seen if he will line up against the Bengals on Sunday.",
        "stats": {
            "GMS": 2,
            "FFPTS": 0
        },
        "fpts": 0,
        "player": "Marcus Allen"
    },
    {
        "player_id": 12297,
        "fname": "Jordan",
        "lname": "Wilkins",
        "team": "IND",
        "team_id": 19,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "FFPTS": 0
        },
        "fpts": 0,
        "player": "Jordan Wilkins"
    },
    {
        "player_id": 12323,
        "fname": "Kalen",
        "lname": "Ballage",
        "team": "PIT",
        "team_id": 18,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "FFPTS": 0
        },
        "fpts": 0,
        "player": "Kalen Ballage"
    },
    {
        "player_id": 56053,
        "fname": "Damarea",
        "lname": "Crockett",
        "team": "DEN",
        "team_id": 8,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "FFPTS": 0
        },
        "fpts": 0,
        "player": "Damarea Crockett"
    },
    {
        "player_id": 56059,
        "fname": "Cullen",
        "lname": "Gillaspia",
        "team": "NYG",
        "team_id": 17,
        "position": "FB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "FFPTS": 0
        },
        "fpts": 0,
        "player": "Cullen Gillaspia"
    },
    {
        "player_id": 57186,
        "fname": "D'Ernest",
        "lname": "Johnson",
        "team": "CLE",
        "team_id": 29,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "FFPTS": 0
        },
        "fpts": 0,
        "player": "D'Ernest Johnson"
    },
    {
        "player_id": 58124,
        "fname": "Jakob",
        "lname": "Johnson",
        "team": "NE",
        "team_id": 1,
        "position": "FB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 1,
            "FFPTS": 0
        },
        "fpts": 0,
        "player": "Jakob Johnson"
    },
    {
        "player_id": 58162,
        "fname": "Khari",
        "lname": "Blasingame",
        "team": "TEN",
        "team_id": 30,
        "position": "FB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "GMST": 1,
            "FFPTS": 0
        },
        "fpts": 0,
        "player": "Khari Blasingame"
    },
    {
        "player_id": 26138330,
        "fname": "Scottie",
        "lname": "Phillips",
        "team": "HOU",
        "team_id": 11,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 1,
            "FFPTS": 0
        },
        "fpts": 0,
        "player": "Scottie Phillips"
    },
    {
        "player_id": 26138353,
        "fname": "Jonathan",
        "lname": "Ward",
        "team": "ARI",
        "team_id": 26,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "FFPTS": 0
        },
        "fpts": 0,
        "player": "Jonathan Ward"
    },
    {
        "player_id": 40549643,
        "fname": "Jake",
        "lname": "Funk",
        "team": "LAR",
        "team_id": 9,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "KRYDS": 70,
            "KRS": 3,
            "KRLNG": 28,
            "KRAVG": 23.329999923706055,
            "AST": 1,
            "FFPTS": 0
        },
        "fpts": 0,
        "player": "Jake Funk"
    },
    {
        "player_id": 40977306,
        "fname": "Khalil",
        "lname": "Herbert",
        "team": "CHI",
        "team_id": 27,
        "position": "RB",
        "injured": 0,
        "injury_type": null,
        "stats": {
            "GMS": 2,
            "KRYDS": 106,
            "KRS": 4,
            "KRLNG": 50,
            "KRAVG": 26.5,
            "FFPTS": 0
        },
        "fpts": 0,
        "player": "Khalil Herbert"
    }
]
export {dataPlayers};